// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
    LZ_ALLOWED_ORIGINS: string[];
    LZ_LOG_SAMPLE_RATE: number;
    LZ_PROD_API_BASE_URL: string;
    LZ_PROD_API_SECRET_KEY: string;
    LZ_R2_BUCKET: R2Bucket;
}
